#ifndef HANDLEBARSQT_GLOBAL_H
#define HANDLEBARSQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HANDLEBARSQT_LIBRARY)
#  define HANDLEBARSQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HANDLEBARSQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HANDLEBARSQT_GLOBAL_H
